#!/usr/bin/env python3

attempt_db_connection         = 'attempt connecting to database'
attempt_eonet_selftest        = 'attempt EONET self-test'
error                         = 'Error'
error_on_event                = 'Event error: {0}'
error_on_command              = 'Command error: {0}'
exception                     = 'Exception'
exception_qualifying_input    = '{0} while qualifying input: {1}'
function                      = 'Function'
load_state                    = 'restore state'
status                        = 'Status'
subroutine_state_schrodinger  = '{0} system state is neither UP nor DOWN.'
task                          = 'Task'
warning                       = 'Warning'
